### ISSUE TITLE
Errors after installing Smiley Palette

### ISSUE THREAD

**Issue by justanotherfoundry** [schriftgestalt/GlyphsSDK#27]
Using Glyphs version 1256:

After installing the Smiley Palette demo, I get the following error:

```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 909, in init
  File "plugin.py", line 30, in settings
    self.logError(traceback.format_exc())
NameError: global name 'traceback' is not defined
```

Maybe related: In my own glyphsPalette, I am getting this error:

```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 929, in init
  File "plugin.py", line 337, in start
    Glyphs.addCallback(self.update, UPDATEINTERFACE)
NameError: global name 'UPDATEINTERFACE' is not defined
```
`UPDATEINTERFACE` is also used by the Smiley Palette but does not cause an error there.

Any hints how I could get addCallback in my palette to work?

**Comment by yanone** [comment]
Just looked into it, because I received a notification on Slack: The error messages don’t make sense in light of the current version of `plugin.py`.
@schriftgestalt, are you always shipping the latest SDK version in the app?

I suppose not, because the SDK recently contained syntax errors that couldn't possibly have been shipped like this.

(Personally I subscribe to the SDK via git and bind it into Glyphs.app on startup, so I always work with the latest version, but that won't work for a shippable plugin)

**Comment by schriftgestalt** [comment]
I have fixed the Smily plugin

**Comment by schriftgestalt** [comment]
and updated the wrapper code
