### ISSUE TITLE
Cant Test Implement Skeleton Plugins

### ISSUE THREAD

**Issue by Nevu** [schriftgestalt/GlyphsSDK#6]
Hello,

I cant test-implement the skeleton-plugins in _GlyphsSDK/ Python Templates/_.
This means, when just grabbing a skeleton-plugin (f.e. ____reporter____) and drop this into my plugins-folder, nothing ist shown ... also for just testing/ hacking ...

some versions before (there were more code in the skeleton-plugins), this effect was available.

Are there any reasons for that?

**Comment by yanone** [comment]
Hi there,

what version of Glyphs are you using,
and what errors do you see?

We're currently re-working the plug-ins extensively and will publicize about it once a stable v2.3 comes out. Much of the code has moved into ObjectWrapper/GlyphsPlugins.py, which is referenced in the skeleton plug-ins.
If you're using a Glyphs version older than 2.3b, get this file and put it where the plug-in code can see it. Glyphs’ Scripts folder might work, otherwise extend the sys.path with a folder that contains the GlyphsPlugins.py.

If you are using 2.3b, please let me know more details about what exactly is not working for you. See Macro window output.

**Comment by Nevu** [comment]
ok, 

I using version 2.2.2 (an checked for updates, glyphs says it is actual).

But I will try your tips and comment if already something wrong.

thx

**Comment by yanone** [comment]
Enable "Show cutting edge versions" in the preferences to get the latest versions. However, they may not be entirely stable. So decide whether you want to produce typefaces, then use the stable versions, or want to play around, then use the cutting edge versions. Personally, I keep two Glyphs.app versions with different file names around, one for each strategy.
